### ISSUE TITLE
Add an arbitrary element to the toolspecific element

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#448]
To allow validation of CPACS files with toolspecific definitions that are not documented in the official CPACS schema, it would be useful to add an 'any' element to the toolspecific node. This any-element should have arbitrary multiplicity [0..*]. This, however, would currently require the definition of toolspecific through a sequence (prescribing the order of child elements) instead of the current all definition (arbitrary order but only [0..0] or [0..1] elements allowed).

Upgrading to XSD Version 1.1 might allow using any cards in combination with all.

**Comment by DLR-LY** [comment]
As discussed via email I agree that we should fix it such that files do not become invalid because of the toolspecific nodes. Your suggestion to use a sequence for the toolspecifics seems to be a good first solution, but forcing the order of the toolspecifics is not practicable. Considering a switch to XSD 1.1 therefore seems to be the cleaner solution. But we should investigate if the used schema checkers actually support it. Especially TIXI should support it as it is the official cpacs interface library.

**Comment by CLiersch** [comment]
I do not think that adding "any"-elements is the right way to extend CPACS, because it somehow contradicts the concept of the Schema specifying the possible content. In the beginning of CPACS, it was discussed to make dataset validation against the schema a mandatory step (e.g. when opening it with TiXI), but it was preferred to leave that out to make extensions, modifications and tests more simple. But when a new part is then used "productively", it should be added to the Schema - even a toolspecific one. If we now allow "any"-elements in the Schema, I fear that the pressure to update _and document_ toolspecific nodes in the official CPACS Schema will decrease.

**Comment by ArneBachmann** [comment]
When we think about long-term archival, I have to agree with CLiersch. In this case we want to store the entire information, including tool-specific settings that lead to the exact result. On the other hand, a lot of process information is not stored anyway (e.g. iterations, outliers, optimizer settings), and CPACS containts only the result of that process in the end.

In practice, however, `<toolspecific>` is mostly used for tools or features in development until they have been integrated into CPACS itself, and concern only the internals of a tool.

One alternative would be to remove toolspecific entirely and let every tool write their tool-specific data in their own namespace. E.g.

  `<mytool:setting>`
    `<mytool:optionswitch>2</mytool:optionswitch>`
  `</mytool:setting>`
and have TIXI manage the additional namespace definition on the root <xml> element.

**Comment by ArneBachmann** [comment]
Cf. #484 for more details on removing the toolspecific node entirely.

**Comment by codingpoets** [comment]
I agree. I think we should strive for individual namespaces for toolspecific nodes.
The structure of the toolspecific nodes should not be coupled to CPACS releases. Toolspecifics should be used according to the tool version and not to the CPACS version that is used.
Seperating the toolspecifics into namespaces allows tool providers to modify the toolspecifics along with their tool version independently of CPACS releases.
Use #484 for further discussion on namespaces for toolspecifics
