### ISSUE TITLE
No possibility to define fuselage standardSheetElementUID without a skin segment

### ISSUE THREAD

**Issue by sdeinert** [DLR-LY/CPACS#449]
Due to the definition of the skinSegments element in the fuselage branch of CPACS, it is not possible to define only a standardSheetElementUID without defining at least one skinSegment.
Generally, this element follows the CPACS rule of skinSegments/skinSegment similar to e.g. wings/wing, which should be kept. However, since the element standardSheetElementUID is located inside of skinSegments, it is not possible to define only this UID without any segment or without invalidating the CPACS file.

From documentation:

> skinSegments/
>  standardSheetElementUID [0, 1]
>  skinSegment [1, *]

Maybe the standardSheetElementUID should be relocated to allow its separate definition?

**Comment by DLR-LY** [comment]
Due to the CPACS rule/convention that you mention, this indeed seems to be an unfortunate place for the definition. I mainly see two options to solve this.

1. We move the "standardSheetElementUID" outside of the "skinSegments" node into the parent "structure" node
2. We add another layer by creating a "skin" element inside the "structure" node and move the "skinSegments" and standardSheetElementUID there.

Personally I am in favor of the second option. What would you suggest?

**Comment by sdeinert** [comment]
The second option sounds good to me as well.
So if I understood correctly this would mean:
<fuselage>
  <structure>
    <skin> [0,1]
      <standardSheetElementUID> [0, 1]
      <skinSegments> [0, 1]
        <skinSegment> [1, *]
...

**Comment by sdeinert** [comment]
Ok again now with the "code":
- fuselage
  - structure
    - skin [0,1]
      - standardSheetElementUID [0,1]
      - skinSegments [0,1]
        - skinSegment [1,*]
...

**Comment by DLR-LY** [comment]
That is what I meant. I'll assign it to the next release.

**Comment by DLR-BT** [comment]
Good idea to solve issue, we agree
