### ISSUE TITLE
wingStringerType does not contain a uID attribute

### ISSUE THREAD

**Issue by RlanderRISCSW** [DLR-LY/CPACS#453]
The CPACS Schema v2.3 does not define a uID attribute in the wingStringerType. Is this intentional or was the attribute just forgotten? We would like to reference a stringer definition and would need it therefore.

**Comment by DLR-LY** [comment]
In the current CPACS definition, only a single stringer node can be defined per cell. Therefore they can be uniquely identified through the cellUID as 'cells/cell[@uID="cellUID"]/stringers'.
The same holds for the default stringer definitions in the upperShell and lowerShell.
You can reference the stringer through the xpath and thus we don't need a uID for the wingStringerType.

**Comment by rmaierl** [comment]
Yes this is true in the current CPACS definition, but only because the explicit stringer definition was not implemented as it was intended from our side.

The explicit stringer should enable different stringer definitions and also more than one stringer set per cell. I attached a slide from the CPACS developer meeting in October 2014 in Aachen for further explanation.

[Explicit_Stringer_Aachen_Maierl.pdf](https://github.com/DLR-LY/CPACS/files/571212/Explicit_Stringer_Aachen_Maierl.pdf)

**Comment by DLR-LY** [comment]
I searched in the issue list and found an old issue on this topic.
https://github.com/DLR-LY/CPACS/issues/401
It looks as if it is refering to the same request and it is marked as solved. Maybe there was a misunderstanding concerning your requirements.
I'm assuming that what you are missing is the possibility to define multiple sets of stringers for each cell or the shells, correct?

**Comment by rmaierl** [comment]
Yes, you are correct.
I am missing the ability to define multiple explicit stringer per cell.

We implemented it, like it is on picture "explicit_stringer_1.jpg at #401" and that is why we also need stringer UIDs for an exact reference.

**Comment by codingpoets** [comment]
Please check if the pull request #500 fits these requirements
