### ISSUE TITLE
Remove use="optional" for attributes

### ISSUE THREAD

**Issue by ArneBachmann** [DLR-LY/CPACS#468]
Remove use="optional" for attributes (this is the default). Enforce use="required" instead where necessary

**Comment by sdeinert** [comment]
Might be a duplicate to #450

**Comment by codingpoets** [comment]
I think this are two different although related issues. this issue concerns all attributes defined in the schema which are optional. Since attributes are optional by default in XSD as defined by W3C the use="optional" can be removed. In #450 we discuss to set use="required" for all attributes with the name "uID".
