### ISSUE TITLE
CPACS 3: Alternative positioning on wingComponentSegment via wingSegment coordinates

### ISSUE THREAD

**Issue by rainman110** [DLR-LY/CPACS#495]
As far as I remember, we decided at the CPACS Developer Meeting, that all geometric elements under the wingComponentSegment node can be positioned in wingSegment coordinates alternatively.

Some of the affected elements are:
 - ribs, spars etc...
 - leading / trailing edge devices
 - wing cells

I could not find any issue with regard to this. Is this still planned for CPACS 3?

I think this is a major but very important change, also for TiGL. In order to integrate this feature into TiGL 3, we need an adapted cpacs 3 schema, which drives our C++ code generator.

**Comment by codingpoets** [comment]
Thank you for the reminder. I am currently struggling with how to structure the changes.
In principle I see three different possibilities to implement the two options.

**1.** add an additional segmentUID node next to eta and xsi. THen, whenever a segmentUID is given the eta and xsi nodes should be interpreted as segment eta xsi coordinates.
  ```
  <parentNode>
    <eta />
    <xsi />
    <segmentUID /> <!-- optional -->
  </parentNode>
```
**2.** add the option as a choice between [eta, xsi] or [etaSeg, xsiSeg, segmentUID]
  ```
  <parentNode>
    <!-- choice 1 start-->
    <eta />
    <xsi />
    <!-- choice 1 end -->
    <!-- choice 2 -->
    <etaSeg />
    <xsiSeg />
    <segmentUID />
    <!-- choice 2 end -->
  </parentNode>
```
**3.** combine both options as described in 2. into their own parent node
  ```
  <parentNode>
    <!-- choice 1 start-->
    <componentSegmentPoint>
      <eta />
      <xsi />
    </componentSegmentPoint>
    <!-- choice 1 end -->
    <!-- choice 2 -->
    <segmentPoint>
      <etaSeg />
      <xsiSeg />
      <segmentUID />
    </segmentPoint>
    <!-- choice 2 end -->
  </parentNode>
```

**Option 1**. is clearly a very reduced approach. It allows the user of the data to switch the interpretation of the eta and xsi nodes depending on the existence of the segmentUID node. A risk of this approach is that without modifications, existing tools might miss the additional segmentUID node and thus misinterpret the point.
**Option 2**. avoids misinterpreting the segment eta xsi values by giving them a different node name. But the drawback is the additional nodes (node names) which need to be processed.
**Option 3**. is very similar to option 2. but keeps eta xsi as the names also for segment eta xsi coordinates and creates an additional intermediate node for both options. This opens up the opportunity to create separate types for both options which can be reused at several locations throughout the schema. This would minimize the effort in case changes are required for the definition of the points and ensures some consistency in the use of eta xsi points. E.g. if we had an etaXsiPointType for componentSegment points we could find all uses throughout the schema to implement the segment coordinate alternative. Also creating an additional type allows us to use xsd:all within the type definition which otherwise would not be possible due to the xsd:choice.

**Comment by rainman110** [comment]
**Option 4.** Just the think out of the box
```xml
<parentNode>
  <eta />
  <xsi />
  <referenceUID />
</parentNode>
```

Where referenceUID is either a segment of a component segment uid.

What do you think about this approach? It is clearly more complicated to implement, but looks very clean from my point of view.

**Comment by codingpoets** [comment]
**Option 4** is very similar to **Option 1** and thus has the same drawback. Only the componentSegmentUID would have to be stated explicitly.

Since the use of componentSegment points is, as far as I know, restrictre to nodes withing the componentSegment node structure thie componentSegmentUID was always assumed implicitly. If we use option 4 it would allow us to move the points also outside of the structure. Although I am not sure if we want to do that.

But I like the idea of option 4 anyway.
What do you think about the drawback mentioned for **Option 1**. Is that something we principally should consider when developing the schema? Or should we rely on tools to check the cpacsVersion given in the header and give an error if not all relevant features were implemented?

**Comment by rainman110** [comment]
> What do you think about the drawback mentioned for Option 1. Is that something we principally should consider when developing the schema? 

To remove the drawback of option 1 and 4, one could add a <point> tag around it. This avoids the problem, that old codes could misinterpret the data.

> Or should we rely on tools to check the cpacsVersion given in the header and give an error if not all relevant features were implemented?

This might be too error prone.

The main drawback with this approach is, that all tools reading cpacs have to be adapted to the new schema. For TiGL, this is not a big issue since we autogenerate the cpacs related code now. For other tools it might by some work though.

**Comment by codingpoets** [comment]
> To remove the drawback of option 1 and 4, one could add a tag around it. 

That would result in option 5, where an etaXsiPointType is introduced similar to option 3.

**Option 5.**
```
<parentNode>
  <etaXsiPoint>
    <eta />
    <xsi />
    <referenceUID />
  </etaXsiPoint>
</parentNode>
```
This also simplifies the reuse in the schema.

> The main drawback with this approach is, that all tools reading cpacs have to be adapted to the new schema. For TiGL, this is not a big issue since we autogenerate the cpacs related code now. For other tools it might by some work though.

The tools would have to change anyway in order not to interpret it in the wrong way in case a segmentUID is given. But by removing the data from the previous position, I assume the awareness of the change is higher.

**Comment by rainman110** [comment]
I think point 5 is the cleanest.

The only issue might be (as you already mentioned): What, if the user specifies a component segment uid from a point that is in some other component segment located?

**Comment by rmaierl** [comment]
I think option 5 is good
I would suggest to rename <referenceUID /> to <segmentUID /> and make it optional.
So that the current component segment is the default.

Other Point:
Is it necessary to define a <etaXsiPoint> outside of a wingComponentSegment?

**Comment by rainman110** [comment]
@codingpoets What's the status of this issue? When are you planning to release CPACS 3?

TiGL 3 is already in good shape with respect to the new component segment support and we are waiting for a new draft of CPACS 3.

**Comment by codingpoets** [comment]
Due to a currently high workload it seems that we will have to postpone the release a bit further. Hopefully until the end of July but possibly even until the end of August. We will adress this issue with high priority.

**Comment by codingpoets** [comment]
> Other Point:
Is it necessary to define a <etaXsiPoint> outside of a wingComponentSegment?

I don't think it is neccessary but it could open up the possibility to position components such as pylons relative to the wing shape although they are not a part of the component.
Not shure whether this is a good idea though.

**Comment by rainman110** [comment]
> I don't think it is neccessary but it could open up the possibility to position components such as pylons relative to the wing shape although they are not a part of the component.
Not sure whether this is a good idea though.

I think this adds some flexibility, which I think is good. It makes the implementation a bit more complicated though.

**Comment by codingpoets** [comment]
I made a suggestion in the PR #515. Please check if you agree with the approach. In the end I implemented it similar to Option 5. but with an explicit choice between segment and componentSegment reference. I wanted to avoid nodes for which the reference is not of a specific type (wingSegment or componentSegment).

**Comment by ProgramAlarm1202** [comment]
Personally, I would prefer that the element names are stable and the content is a choice of wingSegment or componentSegment. This would allow for a vectorized processing. The element `<referenceType>` would be mandatory.

```
<parentNode>
  <etaXsiPoint>
    <eta />
    <xsi />
    <referenceUID />
    <!-- choice 1 start-->
    <referenceType>componentSegment</referenceType>
    <!-- choice 1 end-->
    <!-- choice 2 start-->
    <referenceType>wingSegment</referenceType>
    <!-- choice 2 end-->
  </etaXsiPoint>
</parentNode>
```
