### ISSUE TITLE
Additional Rib positioning @ Spar position

### ISSUE THREAD

**Issue by rmaierl** [DLR-LY/CPACS#533]
The wing rib start and end positioning need the additional possibility to be defined at spar positionings.
It is crucial for a structural analysis to maintain a connected load-path in the wing structure.

The Value etaStart in the wingRibsPositioningType should be replaced by a choice between etaStart and sparPostionStartUID.

The Value etaEnd in the wingRibsPositioningType should be replaced by a choice between etaEnd and sparPostionEndUID.

Attached you will find a CPACS example and a figure of the structure

[refWing_xml.txt](https://github.com/DLR-LY/CPACS/files/1642840/refWing_xml.txt)

![refwing_structure](https://user-images.githubusercontent.com/10923333/35098725-a254078a-fc55-11e7-89b4-cccae6aa3e66.png)

**Comment by kngbuzzo** [comment]
This is an interesting proposal. It is true, that there is no explicit way to couple ribs to spar positions right now. Implicit connections by giving the same eta value will break once the spar position value changes, because there is no way of knowing where to look for updates, so there is some added value in having a second option. Furthermore, the proposal would help reduce data redundancy.

**Comment by codingpoets** [comment]
Please check the implementation in #546
