### ISSUE TITLE
Change/clarify explicit stringer definition

### ISSUE THREAD

**Issue by bernhardmgruber** [DLR-LY/CPACS#535]
The explicit definition of the wingStringerType leaves all parameters optional.

If the <numberOfStringers> element is not specified, it defaults to 0. This is quite meaningless, as this allows to define a <stringer> element which defines no stringers. After discussion with @rmaierl we think the default value should be changed to 1.

Furthermore, the angleReference parameter specifies: "If the reference of the stringer angle shall be different from the default implementation then this parameter may be set". This leads to confusion about what the "default implementation" is. We would like to have one of the specified values here as default (e.g. leadingEdge, maybe also globalY).

What are your thoughts?

**Comment by codingpoets** [comment]
As described in #511 the options cannot be made as suggested because that leads to a name clash in XSD. We would have to add an additional node layer to realize it. Please continue this topic in #511.

The default value is described in the "angle" description and illustrated in the remarks section. 

> the reference axis for the stringer angle is defined by the two leading edge  points of the 'from'- and the 'to'-element of the componentSegment definition.

And the z direction of the reference axes is depicted perpendicular to that reference axis and the wings x-axis.

**Comment by DLR-LY** [comment]
Closed with #557
